plugins:
  - jekyll-polyglot
  - jekyll-minifier
languages:                   ["en", "es", "de", "it"]
default_lang:                "en"
exclude_from_localization:   ["assets", "images", "css", "README.md", "manifest.json", "humans.txt", "sitemap.xml"]
parallel_localization:       true
a_rootpage:                  "https://jamulus.io"
githubrepoeditbase:          "https://github.com/jamulussoftware/jamulussoftware.github.io/edit/changes"
blognewpage:                 "https://github.com/jamulussoftware/jamuluswebsite/new/changes/blog/?value=Set%20filename%20and%20front%20matter&message=New%20blog%20post"
exclude:                     ["README.md", "Gemfile.lock", "Gemfile", "CONTRIBUTING.md"]
jekyll-minifier:
  remove_intertag_spaces:    true
  remove_spaces_inside_tags: true
  remove_multi_spaces:       true
  compress_json:             true
  exclude:                   "sitemap.xml"
excerpt_separator: <!--more-->
pagination:
  enabled: true
  # Set to 'true' to enable pagination debugging. This can be enabled in the site config or only for individual pagination pages
  debug: false
  # The default document collection to paginate if nothing is specified ('posts' is default)
  collection: 'posts'
  # How many objects per paginated page, used to be `paginate` (default: 0, means all)
  per_page: 10
  # The permalink structure for the paginated pages (this can be any level deep)
  permalink: '/page/:num/' # Pages are index.html inside this folder (default)
  #permalink: '/page/:num.html' # Pages are simple html files
  #permalink: '/page/:num' # Pages are html files, linked jekyll extensionless permalink style.

  title: ':title - page :num'
  # Limit how many pagenated pages to create (default: 0, means all)
  limit: 0

  # Optional, defines the field that the posts should be sorted on (omit to default to 'date')
  sort_field: 'date'

  # Optional, sorts the posts in reverse order (omit to default decending or sort_reverse: true)
  sort_reverse: true
 # Optional,omit or set both before and after to zero to disable.
 # Controls how the pagination trail for the paginated pages look like.
  trail:
    before: 2
    after: 2
